insert into person ( first_name, last_name, email) values ('Ali', 'Matys', 'amatys0@wp.com');
insert into person ( first_name, last_name, email) values ('Giacopo', 'Alekseev', 'galekseev1@goo.gl');
insert into person ( first_name, last_name, email) values ('Olivero', 'Dwine', 'odwine2@bizjournals.com');
insert into person ( first_name, last_name, email) values ('Cart', 'Axston', 'caxston3@istockphoto.com');
insert into person ( first_name, last_name, email) values ('Geordie', 'Grimstead', 'ggrimstead4@scientificamerican.com');
insert into person ( first_name, last_name, email) values ('Alvinia', 'Adran', 'aadran5@cnn.com');
insert into person ( first_name, last_name, email) values ('Willi', 'Rebichon', 'wrebichon6@comsenz.com');
insert into person ( first_name, last_name, email) values ('Hakim', 'Roch', 'hroch7@tamu.edu');
insert into person ( first_name, last_name, email) values ('Hermina', 'Guillou', 'hguillou8@sphinn.com');
insert into person ( first_name, last_name, email) values ('Georgie', 'Dewen', 'gdewen9@spotify.com');
insert into person ( first_name, last_name, email) values ('Leandra', 'Harbertson', 'lharbertsona@businessinsider.com');
insert into person ( first_name, last_name, email) values ('Livvyy', 'Beddis', 'lbeddisb@jigsy.com');
insert into person ( first_name, last_name, email) values ('Avis', 'Ewens', 'aewensc@nih.gov');
insert into person ( first_name, last_name, email) values ('Annadiana', 'Feacham', 'afeachamd@thetimes.co.uk');
insert into person ( first_name, last_name, email) values ('Berta', 'Jemmison', 'bjemmisone@cnbc.com');
insert into person ( first_name, last_name, email) values ('Dolley', 'Greggor', 'dgreggorf@tripadvisor.com');
insert into person ( first_name, last_name, email) values ('Boniface', 'Geoghegan', 'bgeoghegang@devhub.com');
insert into person ( first_name, last_name, email) values ('Fenelia', 'Bartolomeo', 'fbartolomeoh@illinois.edu');
insert into person ( first_name, last_name, email) values ('Nona', 'Gaskin', 'ngaskini@creativecommons.org');
insert into person ( first_name, last_name, email) values ('Rosette', 'Kenaway', 'rkenawayj@fc2.com');
insert into person ( first_name, last_name, email) values ('Adriano', 'Warsop', 'awarsopk@unesco.org');
insert into person ( first_name, last_name, email) values ('Tamar', 'Wimbury', 'twimburyl@prlog.org');
insert into person ( first_name, last_name, email) values ('Griffie', 'Goodoune', 'ggoodounem@hc360.com');
insert into person ( first_name, last_name, email) values ('Blanch', 'Sweet', 'bsweetn@github.com');
insert into person ( first_name, last_name, email) values ('Alec', 'Muggeridge', 'amuggeridgeo@fastcompany.com');
insert into person ( first_name, last_name, email) values ('Atlante', 'Rewan', 'arewanp@barnesandnoble.com');
insert into person ( first_name, last_name, email) values ('Fee', 'Ibbotson', 'fibbotsonq@spotify.com');
insert into person ( first_name, last_name, email) values ('Kliment', 'Wormstone', 'kwormstoner@infoseek.co.jp');
insert into person ( first_name, last_name, email) values ('Isabella', 'Poat', 'ipoats@wp.com');
insert into person ( first_name, last_name, email) values ('Neda', 'Verrell', 'nverrellt@patch.com');
insert into person ( first_name, last_name, email) values ('Rosabelle', 'Garfit', 'rgarfitu@yelp.com');
insert into person ( first_name, last_name, email) values ('Garrik', 'Font', 'gfontv@uiuc.edu');
insert into person ( first_name, last_name, email) values ('Alon', 'Tibbles', 'atibblesw@t-online.de');
insert into person ( first_name, last_name, email) values ('Korrie', 'Iacobini', 'kiacobinix@nature.com');
insert into person ( first_name, last_name, email) values ('Venita', 'Bodechon', 'vbodechony@comcast.net');
insert into person ( first_name, last_name, email) values ('Collette', 'Eouzan', 'ceouzanz@about.me');
insert into person ( first_name, last_name, email) values ('Ambur', 'Gokes', 'agokes10@odnoklassniki.ru');
insert into person ( first_name, last_name, email) values ('Devinne', 'Pedgrift', 'dpedgrift11@yandex.ru');
insert into person ( first_name, last_name, email) values ('Jeromy', 'Cato', 'jcato12@aboutads.info');
insert into person ( first_name, last_name, email) values ('Fabian', 'Giacovelli', 'fgiacovelli13@skype.com');
insert into person ( first_name, last_name, email) values ('Audrey', 'Jadczak', 'ajadczak14@bandcamp.com');
insert into person ( first_name, last_name, email) values ('Kristien', 'Catford', 'kcatford15@cyberchimps.com');
insert into person ( first_name, last_name, email) values ('Garwin', 'Pagelsen', 'gpagelsen16@alexa.com');
insert into person ( first_name, last_name, email) values ('Galina', 'Hodge', 'ghodge17@state.tx.us');
insert into person ( first_name, last_name, email) values ('Lombard', 'Rahl', 'lrahl18@google.it');
insert into person ( first_name, last_name, email) values ('Sergeant', 'Breckenridge', 'sbreckenridge19@va.gov');
insert into person ( first_name, last_name, email) values ('Tedda', 'Lampkin', 'tlampkin1a@nifty.com');
insert into person ( first_name, last_name, email) values ('Michaela', 'Mingardo', 'mmingardo1b@google.it');
insert into person ( first_name, last_name, email) values ('Brittne', 'Sumsion', 'bsumsion1c@wufoo.com');
insert into person ( first_name, last_name, email) values ('Brena', 'Portchmouth', 'bportchmouth1d@github.io');

insert into event (host_id, title, description, date_of_event, location) values (18, 'That Championship Season', 'Enhanced discrete moderator', '2020-09-04', '9982 Coleman Terrace');
insert into event (host_id, title, description, date_of_event, location) values (32, 'Next Three Days, The', 'Reactive high-level infrastructure', '2020-08-30', '446 Forest Run Trail');
insert into event (host_id, title, description, date_of_event, location) values (36, 'In the Folds of the Flesh', 'Cloned well-modulated functionalities', '2020-07-18', '74 Kenwood Trail');
insert into event (host_id, title, description, date_of_event, location) values (16, 'Something Wild', 'Streamlined scalable moderator', '2020-12-23', '5 Manufacturers Way');
insert into event (host_id, title, description, date_of_event, location) values (20, 'Boys Don''t Cry', 'Digitized tangible implementation', '2021-02-02', '25384 Swallow Plaza');
insert into event (host_id, title, description, date_of_event, location) values (42, 'Wu Tang Master (Tian shi zhuang xie)', 'Extended tertiary open system', '2020-05-11', '056 Carey Terrace');
insert into event (host_id, title, description, date_of_event, location) values (4, 'Black Dog', 'Persevering clear-thinking database', '2020-07-08', '87861 Pennsylvania Crossing');
insert into event (host_id, title, description, date_of_event, location) values (46, '8: The Mormon Proposition', 'Centralized object-oriented Graphical User Interface', '2020-07-08', '8409 Iowa Crossing');
insert into event (host_id, title, description, date_of_event, location) values (10, 'Hansel & Gretel', 'Quality-focused tangible focus group', '2020-06-07', '7828 Lillian Plaza');
insert into event (host_id, title, description, date_of_event, location) values (13, 'The Castle of Fu Manchu', 'Multi-tiered scalable strategy', '2021-01-20', '6956 Nelson Pass');

insert into invitation (event_id, guest_id, attendance) values (6, 40, 'NO_RESPONSE');
insert into invitation (event_id, guest_id, attendance) values (2, 30, 'NOT_ATTENDING');
insert into invitation (event_id, guest_id, attendance) values (7, 42, 'ATTENDING');
insert into invitation (event_id, guest_id, attendance) values (2, 10, 'NO_RESPONSE');
insert into invitation (event_id, guest_id, attendance) values (7, 22, 'NO_RESPONSE');
insert into invitation (event_id, guest_id, attendance) values (10, 42, 'MAYBE');
insert into invitation (event_id, guest_id, attendance) values (1, 8, 'NO_RESPONSE');
insert into invitation (event_id, guest_id, attendance) values (5, 43, 'NO_RESPONSE');
insert into invitation (event_id, guest_id, attendance) values (10, 10, 'NOT_ATTENDING');
insert into invitation (event_id, guest_id, attendance) values (3, 22, 'NO_RESPONSE');